version: '3'

services:
  peatio:
    build:
      context: peatio
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - db
      - redis
      - rabbitmq
    ports:
      - "8080:8080"
    environment:
      - RAILS_ENV=development
      - DATABASE_HOST=db
      - DATABASE_USER=root
      - DATABASE_PASS=changeme

  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: changeme
      MYSQL_DATABASE: peatio_development
      MYSQL_USER: peatio
      MYSQL_PASSWORD: changeme

  redis:
    image: redis:alpine
    restart: always

  rabbitmq:
    image: rabbitmq:alpine
    restart: always

volumes:
  db_data:
